### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#12]
Ich habe den Websocket serverseitig implementiert und eine kleine Testseite implementiert, bin da aber auf ein Problem gestoßen.
In dem Application Controller, wo auch deine Methode zum Testen des LoadWorker ist, erkennt der die routes und *.scala.html nicht mehr. Ich habe keine Ahnung was da los ist, könntest du mal gucken, ob das bei dir funktioniert? Ich habe nur drei Zeilen im Application Controller hinzugefügt um den Socket bereitzustellen, an deinem Code habe ich nichts geändert.

**Comment by alex-laitenberger** [comment]
Hallo Patrick - ich habe die Routes und den Application Controller mit etwas Gefummel debugged.
Jetzt kommen hier aber sehr viele Compiler Errors in den Aktoren und Messages der Aktoren.
Für mich ist es sehr schwer, zu entwickeln, wenn nach dem nächsten Pull deines Commits so viele Compiler Errors auftauchen. Ich muss dann jedesmal sehr lange debuggen und mich in deine Sachen eindenken. Lass uns bitte nur Sachen pushen, die clean laufen, ok?

Ich hoffe du benutzt auch dieses Aktivator Build Tool und debugst mit dem Activator Web Tool. Da stehen auch immer die Fehler und die Zeilen der Fehler drin.

![activator build tool - compilation errors](https://cloud.githubusercontent.com/assets/9436113/7614481/4dfbfb52-f997-11e4-8081-82bb51b9ccf4.jpg)

**Comment by autarchprinceps** [comment]
Die Fehler die ich so bei dir sehe (bei mir habe ich keine) sind alle: cannot find symbol.
Das heißt, dass er bei dir ein Problem mit den Frameworks hat. Ich weiß nicht genau warum, aber JsString ist Teil von Play, das habe nicht ich geschrieben.

**Comment by autarchprinceps** [comment]
Ich glaube du hast den Fehler, der bei mir auftrat korrekt gefixed, ich kriege keine Fehler mehr im Application Controller.
Ich werde dann mal versuchen, ob ich den Websocket zum laufen kriege.

Falls du gar nicht weiterkommst mit den Linker Errors, kannst du alternativ ja auch mit dem Researchthema anfange. Ich habe eine Präsi erstellt und meine Idee für einen Grobaufbau in das Inhaltsverzeichnis gepackt.
Mit der Präsi müssen wir natürlich aufpassen, gleichzeitig ändern und mergen geht da gar nicht.
Ich werde heute & morgen, falls ich für das Researchthema etwas tue, ausschließlich in unserem Wiki oder an Diagrammen arbeiten. Wenn du also an der Präsi etwas machen willst, ich werde keine Commits machen, die damit im Konflikt stehen könnten.

Im Vorhinein, wenn du irgendwas von dem, was ich einfach so entschieden haben, definitiv anders machen würdest (Aktorarchitektur, Präsi Design oder Aufbau, UI Mockup, ...), sieh das was ich gemacht habe ruhig nur als Vorschlag an, du kannst ruhig Dinge fundamental ändern, wenn du willst.

**Comment by autarchprinceps** [comment]
Ich habe den Websocket mit einem Websockettesterclient (nicht meiner tws.html) getestet.
Mittlerweile geht definitiv register, login, logout & store plan. Ich habe noch ein Problem damit aus Strings wieder ObjectIds zu machen. Muss ich mich nochmal durch die API-Documentation clicken.

Aber ansonsten funktioniert das ganze so weit gut. Ich habe auch in der DB geguckt, mein User und mein Tesplan sind korrekt gespeichert. Testrun kann ich so nicht testen, bis die ObjectId des Testplans korrekt aus dem Input generiert wird, aber du hast ja einen kurzen Test des LoadWorkers gemacht.
Wirklich ungetestet ist als nur noch der LoadRunner Aktor.
