### ISSUE TITLE
WS-API

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#13]
### From Client to Backend

Types:
login, register, logout, store plan, start run, all plans, load plan, load run
### From Backend to Client

Types:
testrun, testplan, login, not auth, error, raw

**Comment by autarchprinceps** [comment]
#### login

Request: {"type":"login","name":"_name_","password":"_password_"}
Antwort:  {"type":"login","description":"Login successful"} or {"type":"error","description":"Login failed: _msg_"}

**Comment by autarchprinceps** [comment]
#### register

Request: {"type":"register","name":"_name_","password":"_password_"}
Antwort:  {"type":"register","description":"Register successful"} or {"type":"error","description":"Register failed: _msg_"}

**Comment by autarchprinceps** [comment]
#### logout

Request: {"type":"logout"}
Antwort:  {"type":"logout","description":"Logged out"}

**Comment by autarchprinceps** [comment]
#### store plan

Request: {"type":"store plan", "testplan":{_testplan_}}

**Comment by autarchprinceps** [comment]
#### _testplan_

{"id":"_BSON-ObjectId_", "path":"_Java-URL_", "connectionType":"HTTP", "numRuns":_uint_, "parallelity":_uint_, "waitBetweenMsgs":_uint_, "waitBeforeStart":_uint_}
Abhängig von Kontext: += {"user":{_user_}}

**Comment by autarchprinceps** [comment]
#### _user_

{"id":"_BSON-ObjectId_", "name":"_String_"}
Abhängig vom Kontext: += {"password":"_String_"}

**Comment by autarchprinceps** [comment]
#### _testrun_

{"id":"_BSON-ObjectId_"}
Abhängig vom Kontext: += {"testplan":{_testplan_}}

**Comment by autarchprinceps** [comment]
#### _raw_

{"iterOnWorker":_uint_, "start":_uint_, "end":_uint_, "testrun":
Abhängig vom Kontext: "_BSON-ObjectId_" or {_testrun (with plan)_}
}

**Comment by autarchprinceps** [comment]
#### all plans

Request: {"type":"all plans"}
Antwort:  foreach plan (individually): {"type":"testplan", "content":{_testplan (withUser)_}}

**Comment by autarchprinceps** [comment]
#### load plan

Request: {"type":"load plan", "id":"_BSON-ObjectId_"}
Antwort:
- {"type":"testplan", "content":{_testplan (withUser)_}}
- foreach run (individually): {"type":"testrun", "content":{_testrun (withPlan)_}}

**Comment by autarchprinceps** [comment]
#### allgemein

Wenn currentUser = null (außer login, register, logout):
{"type":"not auth", "description":"Not authenticated"}

Alle Exceptions beenden WebSocket (insbesondere auch Json parse error oder wrong type)

**Comment by autarchprinceps** [comment]
#### Testruns

Request:
- Neuer Durchlauf: {"type":"start run", "testplan":"_BSON-ObjectId_"}
- Aus Datenbank laden: {"type":"load run", "id":"_BSON-ObjectId_"}

Antwort:
- {"type":"testrun", "content":{_testrun (with plan)_}
- foreach request individually: {"type":"raw", "content":{_raw (testrun: id only)_}}

**Comment by alex-laitenberger** [comment]
Hey - also zum store Testplan - im Testplan:
Was ist  "waitBeforeStart":uint und in welchem Kontext muss ein User mitgegeben werden?
Und die BSON ID kann ich ja nicht senden, die wird doch von Mongo generiert.
Und genau hier ist auch mein Problem, dass ich dir letztens mitteilen wollte: Wenn ich einen Testplan store und ihn anschließend ausführen möchte, habe ich als Client keine Ahnung ob der Testplan bereits gespeichert wurde oder nicht. Wenn ich in einer Tabelle die ausführbaren Testplane einfügen möchte, brauche ich nach dem Store Testplan eine Bestätigung vom Server dass sich in der Testplan Liste was geändert hat. Ansonsten müsste ich einfach auf Vermutung hin den Server nochmal nach allen Testplänen fragen. Ich finde das nach wie vor unnötig umständlich. Wenn ich einen Testplan im Client ausgefüllt habe, möchte ich ihn einfach starten können. Wenn Du ihn unbedingt noch gespeichert haben möchtest, dann mach das doch einfach zusätzlich im Server. Warum so kompliziert eigentlich?

**Comment by alex-laitenberger** [comment]
nächste Frage: was kommt in numRuns/Parallelity rein, was soll das bedeuten?
Ich war bisher davon ausgegangen, dass wir beispielsweise 1000 Requests, Parallelität 10 angeben können und dann schießen 10 Aktoren parallelel 100 Requests ab.

**Comment by autarchprinceps** [comment]
# waitBeforeStart

ist die Verzögerung, bevor die Loadworker anfangen Requests zu senden. Der Gedanke dahinter war, dass man einen Testrun starten kann und dann vllt zum Taskmanager wechseln, oder so kann, bevor der Test beginnt.
Das kannst du entweder auf 0 setzen, oder es vom Nutzer setzen lassen.

# numRuns

ist pro Worker, d.h. 10 parallelity 1000 runs -> insgesamt 10000 requests

**Comment by autarchprinceps** [comment]
Antworten ist so eine Sache. Eine wirkliche Antwort kann in Akka nicht erstellt werden. Ich kann wenn du willst nach dem Speichern eines Plans dessen Id bis zum Client zurückschicken, aber den Kontext, dass das eine Antwort auf deinen Request ist, kann ich nicht bereitstellen.
Du kannst wie gesagt alle Testpläne mit ihren Ids abfragen, und ich packe eine solche Rückmeldung rein, falls du meinst, dass dir das weiterhilft.

**Comment by autarchprinceps** [comment]
{"type":"stored plan","id":"_ObjectId_"} implementiert.
Es wird erst gesendet, wenn der Testplan von MongoDB acknowledged und ins Journal geschrieben ist. Es sollte also wirklich gespeichert sein.

**Comment by alex-laitenberger** [comment]
top. Genau die fang ich ab und setze den neuen Plan dann in die Tabelle etc.
Ich probiers gleich mal aus..

**Comment by alex-laitenberger** [comment]
also ich bekomm keine Info vom Server nach Store Testplan. Das Store funktioniert aber, also ich kriege den Plan dann unter get all Testplans.

`DEBUG: UIInstance {"type":"store plan","testplan":{"path":"http://localhost","connectionType":"HTTP","numRuns":200,"parallelity":5,"waitBetweenMessages":0,"waitBeforeStart":0}}
DEBUG: UIInstance Storing plan
DEBUG: UIInstance Stored plan`

**Comment by autarchprinceps** [comment]
hmm wenn ich das bei mir in den socket einfüge kriege ich einen JSON Parse error.

**Comment by alex-laitenberger** [comment]
bekommst du denn ne Rückmeldung für nen Stored Plan?

Also die Pläne kommen ja an...

`Server: {"type":"all plans","content":[{"id":"557ad18d1759af093bdd274b","path":"http://localhost","connectionType":"HTTP","numRuns":50,"parallelity":2,"waitBetweenMsgs":0,"waitBeforeStart":1},{"id":"557aecc01759af093bdd274c","path":"http://localhost","connectionType":"HTTP","numRuns":359,"parallelity":2,"waitBetweenMsgs":0,"waitBeforeStart":1},{"id":"557c1f660779d5b5f2b53e60","path":"http://localhost","connectionType":"HTTP","numRuns":100,"parallelity":5,"waitBetweenMsgs":0,"waitBeforeStart":0},{"id":"557c1f660779d5b5f2b53e5f","path":"http://localhost","connectionType":"HTTP","numRuns":100,"parallelity":5,"waitBetweenMsgs":0,"waitBeforeStart":0},{"id":"557c1fa30779d5b5f2b53e61","path":"http://localhost","connectionType":"HTTP","numRuns":200,"parallelity":5,"waitBetweenMsgs":0,"waitBeforeStart":0},{"id":"557c20680779d5b5f2b53e62","path":"http://localhost","connectionType":"HTTP","numRuns":200,"parallelity":5,"waitBetweenMsgs":0,"waitBeforeStart":0},{"id":"557c22ec0779d5b5f2b53e64","path":"http://localhost","connectionType":"HTTP","numRuns":200,"parallelity":5,"waitBetweenMsgs":0,"waitBeforeStart":0}]}"`

**Comment by autarchprinceps** [comment]
ich habe es nochmal ohne kopieren versucht, jetzt habe ich eine dead letters, hattest du auch dead letters?
Ja das wird in der DB gespeichert.

**Comment by alex-laitenberger** [comment]
jep

`[INFO] [06/13/2015 14:56:32.734] [default-akka.actor.default-dispatcher-4] [akka://default/deadLetters] Message [play.api.libs.json.JsObject] from Actor[akka://default/user/$a#1767515921] to Actor[akka://default/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

**Comment by alex-laitenberger** [comment]
aber gespeichert wird der Plan scheinbar trotzdem

**Comment by autarchprinceps** [comment]
Ja, aber akka schaft es nicht die Nachricht an die UIInstance zurückzuschicken. Das ist was Dead Letters bedeutet "Tote Briefe" halt.
Ich verstehe aber noch nicht warum, ich meine alle anderen sachen müssen ja auch von der DB an die UIInstance versendet werden, und das funktioniert ja ohne Probleme.

**Comment by autarchprinceps** [comment]
Warte ich glaub ich habs, funktioniert jetzt bei mir. Ist gepushed.

**Comment by alex-laitenberger** [comment]
jo läuft, Top !

**Comment by alex-laitenberger** [comment]
was war´s?

**Comment by autarchprinceps** [comment]
getSender funktioniert nicht in Future-Ausführung

**Comment by alex-laitenberger** [comment]
ok bisher läuft alles mit Anlegen des Testplans und Ausführen.
Was ich noch brauche, ist ein Request 
"type": "all Testruns",  "testplanID": "123456"
der mir dann alle Testruns zu einem bestimmten Testplan aus der Datenbank holt.
Bisher kann ich mir nur die merken, die ich selbst in der Session ausgeführt habe.

**Comment by autarchprinceps** [comment]
"type":"load testplan" macht das
