### ISSUE TITLE
runTestplan

### ISSUE THREAD

**Issue by alex-laitenberger** [autarchprinceps/Reactive-Load-Generator#14]
Hey - run testplan wirft bei mir folgenden Fehler - woran könntest das liegen?

[ERROR] [06/12/2015 16:02:24.470] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] None.get
java.util.NoSuchElementException: None.get

**Comment by alex-laitenberger** [comment]
den Testplan sollte es geben, er wird mir vorher ausgegeben unter get all testplans

**Comment by alex-laitenberger** [comment]
@autarchprinceps

**Comment by autarchprinceps** [comment]
None.get heißt, dass er etwas nicht gefunden hat. Da müsste es eine Codezeile zu geben. Wenn du die mir gibst, kann ich dir sagen, was nicht gefunden wird.

**Comment by alex-laitenberger** [comment]
Ok mit dem neuen commit läuft es jetzt, vielleicht hast du´s versehentlich gefixt ;-)
