### ISSUE TITLE
load all Testplans

### ISSUE THREAD

**Issue by alex-laitenberger** [autarchprinceps/Reactive-Load-Generator#15]
wenn ich die Testpläne refreshe brauche ich sie vom Server direkt als Array. Es funktioniert nicht, wie es momentan ist, dass der Server jeden Testplan anschließend als einzelne Nachricht raushaut.

**Comment by alex-laitenberger** [comment]
also z.B.:
"type":"allTestplans",
"content": "[{testplan1},{testplan2}]"

**Comment by alex-laitenberger** [comment]
@autarchprinceps

**Comment by autarchprinceps** [comment]
Habe ich gemacht:
all plans: {
    type: "all plans",
    content: [_testplan (without user)_]
}
all runs: {
    type: "all runs",
    testplan: "_ObjectId_",
    content: [_testrun (without plan)_]
}

Ich habe die Tests noch nicht angepasst. Das muss einer von uns irgendwann noch machen.

**Comment by alex-laitenberger** [comment]
top, läuft
