### ISSUE TITLE
Präsi

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#16]
Ich habe für die Präsi mal eine Aufteilung erstellt. Irgendwelche Ergänzungen deinerseits?

Als Aufteilung würde ich sagen:
- Architektur:
  - Allgemein, WebSocket, Play Routen & Controller: @alex-ellpunkt 
  - Aktorsystem: @autarchprinceps
  - DB, Java Datenstruktur: @autarchprinceps
- UI:
  - Allgemein: @alex-ellpunkt 
  - Graph: @autarchprinceps
- Reflexion: @?

**Comment by alex-laitenberger** [comment]
ich hab mal ein paar Slides zu UI und Client-Prozessen und dem reaktiven Konzept eingefügt, die ich vortrage.

**Comment by autarchprinceps** [comment]
Willst du den Graph vortragen? Ich hatte ja die Reflexion in PowerPoint gemacht. Wenn ich die auch vortrage, wäre es wahrscheinlich nicht schlecht, wenn du den Graph und D3 vorstellst.

**Comment by autarchprinceps** [comment]
Ich habe alles von mir fertig commited und mir alles noch mal angeguckt. Ich glaub das sieht so gut aus.
Das einzige was noch fehlt ist die allgemeine Architekturübersicht 
(also so in der Richtung:
- UI->WebSocket->Aktorsystem->Server
- ________________________->DB
- Graph.onChange <- WebSocket

oder so, irgendwas simples halt als Überblick).

Ich hatte das so verstanden, dass du das Kapitel machen wolltest und ich beim Aktorsystem anfange. Wenn du willst, dass ich das mache, müsstest du mir Bescheid sagen, sonst lasse ich das offen.
Ich habe das Inhaltsverzeichnis etwas verändert, aber du kannst das gerne auch noch anpassen, wenn dir das noch nicht ganz gefällt.

**Comment by alex-laitenberger** [comment]
done !
