### ISSUE TITLE
Terminplan

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#2]
Ich habe mal einen Terminplan erstellt (unter Dokumentation).

Guck bitte mal drüber und pass den an, falls nötig (Bis Mi, ich schicke denen das am Do vormittag)

Gleiches gilt natürlich noch für den Architekturplan, aber an dem arbeite ich noch.

**Comment by alex-laitenberger** [comment]
ich hab die letzteren Termine mal nach hinten aufgebohrt, weil wir ja insgesamt noch bis zum 19. Juni Zeit haben bis das Projekt präsentiert werden muss, oder hab ich was übersehen?

**Comment by autarchprinceps** [comment]
Glaubst du, dass die Architektur soweit gut ist bzw. ausreicht, oder soll ich noch mehr dokumentieren?

**Comment by alex-laitenberger** [comment]
ich finds gut
