### ISSUE TITLE
Architekturentscheidung - Pull oder Push

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#3]
Soll unsere Graph sich seine Daten per Pull über die Websocketverbindung holen (per Timer, falls das während des Durchlaufs ist), oder soll unser System die Daten sobald sie verfügbar sind rauspushen?

**Comment by alex-laitenberger** [comment]
ich vermute der Push des Systems an die Graph-Oberfläche wäre cooler, v.a. weil wir die Last über den Load-Generator dann auch an unseren Webbrowser weiterleiten und sehen können, wann der einknickt, oder?

**Comment by autarchprinceps** [comment]
Das hört sich fast eher nach einem Grund für Pull an :D
Ich habe es in der Architektur mal noch beides drinne, wir können ja mal erstmal testen, ob Push überhaupt geht, oder ob dass den Websocket zum Glühen bringt.
