### ISSUE TITLE
Webdesign

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#5]
Welches Framework sollen wir für das Design benutzen?

**Comment by autarchprinceps** [comment]
Was gibt es überhaupt:
- Bootstrap
- [Polymer](https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-input)
- Dojo?

**Comment by autarchprinceps** [comment]
Wahnsinniger Vorschlag: Theoretisch könnten wir das ganze in einer Website unterbringen und auf Basis der Websocketverbindungen die UI von Javascript aus ändern.

**Comment by autarchprinceps** [comment]
Was ist mit AngularJS? Ich habe es noch nie benutzt.

Oder wir benutzen im Frontend RxJS, wie das in der ersten Vorlesung gezeigt wurde. Dann würden wir die UI auch Reactive anpassen. Die Observermethoden würden dann halt auch den d3js-Code enthalten.

**Comment by autarchprinceps** [comment]
http://materializecss.com

https://callemall.github.io/material-ui/#/

**Comment by alex-laitenberger** [comment]
eine Website in der wir mit JavaScript eine Websocketverbindung in unser Backend aufbauen würde denke ich Sinn machen. Die Beispielprojekte im activator haben das meine ich auch so gemacht. Ich habe gerade nur Probleme das play - akka - angular - websocket Beispielprojekt ans Laufen zu bekommen. Wenn das funktioniert hätten wir auf alle Fälle schonmal guten Input für angular..

**Comment by autarchprinceps** [comment]
[angular.js material](https://material.angularjs.org)

**Comment by autarchprinceps** [comment]
[material bootstrap](https://fezvrasta.github.io/bootstrap-material-design/)

**Comment by autarchprinceps** [comment]
Ich habe den WebSocket implementiert und Mockups wie ich mir die UI vorstellen könnte erstellt. Ich bin was CSS angeht ziemlich ungeschickt. Willst du vielleicht dir eine UI Bibliothek raussuchen und mit dem Websocket die UI implementieren. Den Graphen integrieren kann vllt besser ich machen, aber es muss ja auch noch der Rest der UI drumherum geschrieben werden.

**Comment by alex-laitenberger** [comment]
Ich kann wegen den Compiler Fehlern unsere Applikation nicht bauen. Daher macht sich das schwierig, am Frontend zu testen und zu entwickeln. Könntest du deine Compiler Fehler mal korrigieren? Wie baust Du eigentlich die Applikation? Bei dir dürfte das doch genausowenig funktionieren..

**Comment by autarchprinceps** [comment]
Hmm, ich kriege keine Compile Errors. Nur Warning: Thread.stop is deprecated.
Ich lasse normalerweise activator run, dist oder test laufen, aber auch IDE compile all funktiontioniert bei mir.

**Comment by autarchprinceps** [comment]
Hast du Scala & Java 8, sonst wird das nicht bauen. Das wäre der einzige Grund, der mir jetzt spontan einfällt, warum das bei mir compiliert und bei dir nicht.

**Comment by autarchprinceps** [comment]
Am Webdesign solltest du aber erstmal in reinem HTML, CSS & vielleicht JS arbeiten, definitiv, wenn das bei dir nicht compiled.
Hast du beschlossen, was du am liebsten als Framework nehmen willst?

**Comment by autarchprinceps** [comment]
Ich habe das andere Issue mal geschlossen, wir müssen die Compile Errors ja nicht in zwei Issues diskutieren und die Problem im Applikation Controller hast du definitiv gefixed.

Dein Screenshot sagt mir aber eindeutig, dass der Plays JSON Klassen irgendwie nicht auflösen kann, die Errors sind alle "cannot find symbol" also die Javaversion eines Linker errors.
