### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by alex-laitenberger** [autarchprinceps/Reactive-Load-Generator#7]
moin - also ich hab die Applikation hier gerade im TypeSafe Activator im Browser offen. Hast du bisher in IntelliJ oder Eclipse gearbeitet (oder nur im TypeSafe Activator?) :-)

Eclipse hätte ich schon vorinstalliert, auch inklusive jEE mit Maven.

Ich würde vorschlagen wir entwickeln in der selben IDE, welche auch immer wir bevorzugen.

**Comment by autarchprinceps** [comment]
Ich habe IntelliJ benutzt, aber mit activator run auf der Konsole das Projekt compiliert / gestartet.
Von da her könnte man wahrscheinlich auch ohne Probleme Eclipse benutzen, aber ich werde das auf jeden Fall nicht tun.
Ich weiß nicht ob Maven ausreicht, du brauchst ja eingentlich noch sbt oben drüber.

Theoretisch sollten von der IDE temporär erzeugtes sowieso von der .gitignore abgefangen werden, aber ich weiß nicht ob die alle nötigen Regeln enthält.

**Comment by alex-laitenberger** [comment]
ist denn IntelliJ so viel besser als eclipse?
Ich habe halt letztes Semester eclipse installiert für maas, netbeans für ooka und denke irgendwie ist es dumm für jedes Projekt eine völlig neue IDE einzurichten.

**Comment by autarchprinceps** [comment]
Benutz von mir aus Eclipse. Das Scala Build Tool bestimmt ja die Ausführung, das sollte Eclipse nicht kaputt machen können.
Ich habe keine Ahnung, ob Netbeans SBT unterstütz. Default glaub ich nicht.

**Comment by alex-laitenberger** [comment]
jo hab mitlerweile ein paar Demo Projekte ans Laufen gebracht. Ich find die activator UI ziemlich komfortabel.. da lässt sich auch ne eclipse projekt Datei generieren, sodass ich damit jetzt erstmal arbeite..

**Comment by autarchprinceps** [comment]
Ich habe auch etwas mit der activator ui rumgespielt um die Aktoren zu verstehen, aber ich würde nicht gerne am Stück Source Code schreiben.
Wenn du die Beispielprojekte durchgearbeitet hast, kannst du ja mal versuchen, ob du den LoadWorker Aktor zum Laufen kriegst.
