### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Reactive-Load-Generator#9]
Ich habe die erste Variante des Graph in d3js fertig. Wenn du willst kannst du dir den auch angucken, dafür musst du nur die Graph.html im d3js-Ordner mit dem Browser öffnen (kein Play, Webserver, ... nötig). Der zeigt Datenpunkte von der Struktur {start: 213, end: 231} (genau wie in unseren Aktorevents) an und aktualisiert sogar bestehende Werte und die Achsen, wenn neue Werte außerhalb des bisherigen Bereichs liegen.

Wenn du die Requests in den LoadWorker implementierst und einen WebSocket zwischen Graph.html und den Aktoren einfügst (und natürlich vorrausgesetzt mein Aktorcode funktioniert, was vielleicht noch etwas debugging benötigt), könnten wir eine erste test- und theoretisch zeigbare lauffähige Version haben.

DB, User und WebUI für den Testplan fehlen dann natürlich immer noch fast völlig, aber das sollte trotzdem schon Ergebnisse anzeigen.

**Comment by alex-laitenberger** [comment]
abgefahren :-) die graph.html sieht schonmal cool aus..

Jo ich setz mich an erstmal an die Requests..

VG!

**Comment by alex-laitenberger** [comment]
so, hab jetzt mal ne kleine testseite mit nem Button eingerichtet, um einen ersten Loadworker Aktor zu starten und einen HTTP-Request abzufeuern. Funktioniert soweit.

**Comment by autarchprinceps** [comment]
Cool.
Du umgehst im Moment noch den LoadRunner und sprichst direkt den LoadWorker an, sind im LoadRunner Bugs, oder machts du das nur, weil es einfacher war für einen ersten Test?

Hast du schon einen Plan, wie der WebSocket einzubinden ist? Momentan ist die Kommunikation ja noch old school post und unidirektional.
